version: '3.8'

services:

  api:
    build: ./
    ports:
      - "4444:4000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.36
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - ./src/database/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "3306:3306"