version: '3.8'

services:

  api:
    build: ./
    ports:
      - "4444:4000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_NAME=universidade_do_bem
      - DB_USER=root
      - DB_PASSWORD=root
      

  mysql:
    image: mysql:8.0.36
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - ./src/database/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
